# MariaDB school server connection 
spring.datasource.url=jdbc:mariadb://cs2800gr15.myweb.cs.uwindsor.ca:3306/cs2800gr15_myadvice
spring.datasource.username=cs2800gr15_myadvice
spring.datasource.password=jU8Ncm5unN9ZhshcSyBm
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.show-sql=true

# Turn off web application type
spring.main.web-application-type=none