# MariaDB (LOCAL) Database Connection
spring.datasource.url=jdbc:mariadb://localhost:3306/[YOUR DB NAME]
spring.datasource.username=root
spring.datasource.password= [YOUR PASSWORD]
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Turn off web application type (no web server needed long term)
spring.main.web-application-type=none

# Optional for debugging hibernate
#logging.level.org.hibernate.boot.model=DEBUG